### ISSUE TITLE
CRUD de Tipos de Problemas

### ISSUE THREAD

**Issue by EricksonFerreira** [KevinSousa/ctic#22]
- [x]  Criar uma View para Adicionar e  Listar os Tipos de Problemas e uma âncora para Editar Tipos de Problemas e excluir o Tipo de Problema
- [x]  Criar uma View para Editar o Tipos de Problemas
- [x]  Criar Controller TipoProblemaController
- [x]  Criar CRUD no Controller TipoProblemaController

**Comment by KevinSousa** [comment]
Finalizado
