### ISSUE TITLE
CRUD de Chamados

### ISSUE THREAD

**Issue by EricksonFerreira** [KevinSousa/ctic#24]
- [ ]  Criar uma View para Adicionar e Editar Chamados
- [ ]  Criar uma View para Listar, Excluir e com um Link para a View Editar Chamados
- [ ]  Criar CRUD no Controller ChamadosController

**Comment by jhonnyfreitas1** [comment]
Bom,  está cadastrando os chamado com o primeiro usuario com id 1 já que a parte de login não  esta construida. possivelmente vai ser alterado após termino da parte de login.
