### ISSUE TITLE
Melhorar o DataTables

### ISSUE THREAD

**Issue by KevinSousa** [KevinSousa/ctic#51]
Eu como usuário do sistema quero poder ver o calendário de reserva do laboratório 
com o scroll desativado.
 
- [x] Remover CDN do Datatables ou  conseguir modificar.

**Comment by EricksonFerreira** [comment]
#### Instalei o Datatable utilizando o que eu aprendi nestes dois videos:
	https://www.youtube.com/watch?v=WKS6kO9zJQI
	https://www.youtube.com/watch?v=7I8HfA5iIRw

#### Coloquei o Datatable em protuguês imitando o codigo deste video: 
	https://www.youtube.com/watch?v=eNXU0uDHJLQ

#### Documentações que eu consultei do datatables:
	https://datatables.yajrabox.com/starter
	https://yajrabox.com/docs/laravel-datatables/master/introduction
