### ISSUE TITLE
Criar README

### ISSUE THREAD

**Issue by KevinSousa** [KevinSousa/ctic#6]

**Comment by ricardomlp** [comment]
Readme:

Sistema de chamados para os laboratórios do IFPE Igarassu

Sistema de abertura de chamados para manutenção dos hardwares nos laboratórios do IFPE campus Igarassu. Pretendemos agilizar a comunicação entre os responsáveis pelos trabalhos, como deixar registrados todas as etapas envolvidas no processo.

Utilizamos o github para controle de versão de arquivos, onde podemos contribuir simultaneamente no mesmo, editando e criando novos arquivos e permitindo que os mesmos possam existir sem o risco de suas alterações serem sobrescritas.

Usamos o Laravel para o desenvolvimento web, que tem como principal característica ajudar a desenvolver aplicações seguras e performáticas de forma rápida, com código limpo e simples, já que ele incentiva o uso de boas práticas de programação.

**Comment by KevinSousa** [comment]
Readme pronto
