### ISSUE TITLE
Adicionar, apenas, número nos campos

### ISSUE THREAD

**Issue by EricksonFerreira** [KevinSousa/ctic#89]
- [ ] Adicione o numero de tombamento do equipamento*  (Restringir somente para numeros)
- [ ] Adicione o numero da Sala*  (Restringir somente para numeros)

**Comment by CleytonVieira** [comment]
Havia um campo que deveria receber, unicamente, números e outro que, obrigatoriamente, só aceitava letras, em razão disso esses campos foram acometidos por restrições as quais dizem respeito a essas características.
